### ISSUE TITLE
Tuning issues present in some ditties

### ISSUE THREAD

**Issue by kieranhj** [kieranhj/pop-beeb#170]
The vgm conversion script has struggled to cope with a couple of the death ditties that use multi-channel FX.

See these [clues](https://bit-shifters.slack.com/files/U1H38HY7Q/F9SBK5VRU/clues___.txt).

**Comment by inversephase** [comment]
@simondotm thinks this is primarily due to the 3.58 vs 4mhz clock. I'm inclined to agree. One thing makes me wonder if there's no an issue from where the bass (noise) channel is being tapped. On SMS noise is tapped from the third square wave channel and on one of the tunes (I'll have to find out which) it sounds like it might be coming from square 2 instead?

**Comment by simondotm** [comment]
Turned out to be a Quad-Tone issue. BBC Micro does not support harmonized tuned periodic noise at the same time as audible channel 2 tone due to its piddly 15-bit LFSR (whereas SMS has 16-bit).

**Comment by mattgodbolt** [comment]
So interested to discover why IP was having so much trouble with this :-)

Thanks for all these bug reports and responses, as a vicarious passer-by,
it's fascinating to hear all about it!

**Comment by inversephase** [comment]
Uh oh, looks like we might have a stalker gents :wink: (or perhaps: a "beebing" tom?)

**Comment by mattgodbolt** [comment]
Hahahahah!

**Comment by simondotm** [comment]
Ok more detailed explanation for interested passers by. :)
https://gist.github.com/simondotm/84a08066469866d7f2e6aad875e598be
